### ISSUE TITLE
Serious bug in gdal_trace_outline (produces broken geometry)

### ISSUE THREAD

**Issue by gbb** [gina-alaska/dans-gdal-scripts#7]
Hi,

I use gdal_trace_outline as part of a workflow to generate national datasets of land use in Norway. This year I took a fresh copy of dan's scripts from master on January 30th, and the resulting map had corrupted polygons all over it.

I went back to the version of dans-gdal-scripts that I previously built from February 2013 and there was no problem.

Then I rebuilt the February 2013 version in case the problem was with some supporting libraries. Again no problems, so it's not the supporting libraries. 

Then I went back and rebuilt the 2015/01/30 version from scratch to check the build was correct, but the corrupted polygons showed up in the same places. 

So it's an algorithm or raster import bug that has been introduced since February 2013.

You can see the effects below. 

![screenshot 020215 1741](https://cloud.githubusercontent.com/assets/4179224/6018520/b157564a-ab97-11e4-80c9-96ba038f0ebf.jpeg)

This first picture shows the problem is affecting pretty much all of our tiles that contain data. You can see the tiling we're using. gdal_trace_outline is getting one tile at a time.

![screenshot 030215 1047](https://cloud.githubusercontent.com/assets/4179224/6018521/b643bd06-ab97-11e4-9cbe-c9babbe6caa2.jpeg)

On the top left, here's a zoomed in version of the buggy output from current stable gdal_trace_outline. Below is the output from gdal_polygonize for a neighbouring tile. To the right is the source tifs for neighbouring tiles.

![screenshot 030215 1048](https://cloud.githubusercontent.com/assets/4179224/6018671/d3fd5ba8-ab98-11e4-8dd2-f8d7c030fc53.jpeg)

Top left - original source tile of the tif. 

![screenshot 030215 1113](https://cloud.githubusercontent.com/assets/4179224/6018674/d7eb30c8-ab98-11e4-91d7-3b94a96be6bc.jpeg)

Top left - output from gdal_trace_outline_201302. (february 2013). 

![screenshot 030215 1118](https://cloud.githubusercontent.com/assets/4179224/6018678/dcf9e7bc-ab98-11e4-8e40-8d4be328a996.jpeg)

Top left - output from gdal_trace_outline_20150130   (rebuilt from scratch).

Flags used are: "POLYGONIZE_FLAGS="-classify -out-cs en -split-polys -dp-toler 0 -bevel-s
ize 0.01 -ogr-fmt 'ESRI Shapefile' -ogr-out ""

Any ideas?

I can give you a diff of the gdal_trace_outline code between the working and broken versions if it's helpful. 

(Also, I notice that the older version of the scripts did a ./configure check for proj4-devel which doesn't happen now. Is that deliberate)?

**Comment by gbb** [comment]
I've emailed you but it's not showing up here. Basically 

Thanks very much for your help and quick reply. TIFF tile - should be fine but I have to ask my section leader and that will take until Thursday morning. Where is the best place to email it (probably 1MB)?

By the way, google for 'topologish' - you are welcome to make a raster of this million polygon simulated map and re-polygonise it using feb13 and current versions for comparison, if it's helpful. Probably a good test case to pick up bugs since it's pretty complex and a known topology.

**Comment by dstahlke** [comment]
My email is dan@stahlke.org, and 1MB should email fine.  I could create a dropbox folder for a larger file.

So, from the pictures above, it looks like what's happening is that the right half of the tile is corrupted?  It looks to me like maybe the raster data is getting corrupted before making it to the polygonizer.  It looks like a television with bad hsync.  But of course it's impossible to diagnose without a test case.

**Comment by dstahlke** [comment]
Okay, fixed now.  Actually, I'm amazed this didn't show up sooner.  I was mistaken about how GDALReadBlock returns data for edge blocks.  This bug would show up for any raster whose width was not a multiple of the block size.

**Comment by gbb** [comment]
Excellent work Dan, thanks! Look forward to testing it out.

It's funny, there's a lot of people out there still using gdal_polygonize
who haven't heard about your scripts yet. I've been mentioning the scripts
to quite a few GIS people.

Perhaps it might be worth putting a post to one of the GDAL mailing lists
to let them know whenever there's a substantial group of changes grouped
together or a big bugfix?

Also, it might be worth tagging a version number onto some nodes of the git
history so that people can refer to them more easily (v1.1, 1.2...). It
would be helpful with bug reporting and it also helps people like myself
who are building other open source tools based on your work. :-)

Anyway thanks again and have a great weekend!

Graeme.

**Comment by gbb** [comment]
Also I'll test this out at the start of next week and let you know if
there's any other funny result.

**Comment by dstahlke** [comment]
I was doing version tags, just forgot to update them for a while.  If 
this bug fix works out, I'll tag it version 0.24.  All my version 
numbers are always less than one for some reason.
